#!/usr/bin/env python3
"""
Vendor the audit engine into the console so the app has no install-time dependency.

The console reuses `camoufox.audit` rather than reimplementing it: the ladder, the
classifier and the safety ceilings are the product, and a second copy would drift.
But the console also has to be shippable as one file that runs on a bare Python, so
the engine is copied in at build time instead of imported from an installed package.

`console/_engine/` is generated. Edit `pythonlib/camoufox/audit/` and re-run this;
`make console-check` (and CI) fail if the copy has drifted.

Run:
    python3 apps/audit-console/sync_engine.py
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import List

APP_DIR = Path(__file__).resolve().parent
REPO_ROOT = APP_DIR.parent.parent
ENGINE_SRC = REPO_ROOT / "pythonlib" / "camoufox" / "audit"
ENGINE_DEST = APP_DIR / "console" / "_engine"

HEADER = """# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/{name}, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""

#: Relative imports the engine makes into the rest of the package. These are all
#: lazy -- inside the browser-rung paths -- so rewriting them costs nothing at
#: import time and keeps L0 runnable with nothing installed.
_IMPORT_REWRITES = (
    ("from ..async_api import ", "from camoufox.async_api import "),
    ("from ..proxy import ", "from camoufox.proxy import "),
)


def _rewrite(body: str) -> str:
    for old, new in _IMPORT_REWRITES:
        body = body.replace(old, new)
    return body


def _iter_sources() -> List[Path]:
    return sorted(p for p in ENGINE_SRC.glob("*.py") if p.name != "__init__.py")


def _render(src: Path) -> str:
    return HEADER.format(name=src.name) + _rewrite(src.read_text(encoding="utf-8"))


def sync(check: bool = False) -> int:
    if not ENGINE_SRC.is_dir():
        print(f"engine source missing: {ENGINE_SRC}", file=sys.stderr)
        return 1

    drift: List[str] = []
    if not check:
        ENGINE_DEST.mkdir(parents=True, exist_ok=True)

    for src in [ENGINE_SRC / "__init__.py", *_iter_sources()]:
        dest = ENGINE_DEST / src.name
        rendered = _render(src)

        if check:
            if not dest.exists() or dest.read_text(encoding="utf-8") != rendered:
                drift.append(src.name)
            continue
        dest.write_text(rendered, encoding="utf-8")

    if check:
        if drift:
            print(
                "console engine is out of date with pythonlib/camoufox/audit: "
                + ", ".join(drift),
                file=sys.stderr,
            )
            print("run: python3 apps/audit-console/sync_engine.py", file=sys.stderr)
            return 1
        print("console engine matches pythonlib/camoufox/audit")
        return 0

    # Drop files whose source is gone, so a removed module does not linger.
    live = {p.name for p in _iter_sources()} | {"__init__.py"}
    for stale in ENGINE_DEST.glob("*.py"):
        if stale.name not in live:
            stale.unlink()
    shutil.rmtree(ENGINE_DEST / "__pycache__", ignore_errors=True)

    print(f"synced {len(live)} modules into {ENGINE_DEST.relative_to(REPO_ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the vendored copy differs from the source, without writing",
    )
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
