# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/evasion.py, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""
The evasion ladder: which defenses hold as the client looks less like a bot.

A single "did we get in?" answer cannot be acted on. If the audit fails at the
top level, the operator learns nothing about *which* control stopped it, so they
cannot tune anything -- they can only turn defenses up, which is how sites end up
with a WAF nobody understands.

Running the same target at increasing levels isolates cause from effect. The
first level whose verdict flips from allowed to detected is the control that is
actually doing the work. Everything below it is already defeated and is dead
weight; everything above it is untested and unknown.

The ladder is ordered by cost, cheapest first, so a cheap defense that holds
means the audit stops early instead of building an elaborate browser for nothing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

__all__ = [
    "EvasionLevel",
    "EVASION_LEVELS",
    "level_by_id",
    "levels_up_to",
]


@dataclass(frozen=True)
class EvasionLevel:
    """
    One rung: a client posture, and how to build it.

    `client` selects the transport shape; `camoufox_options` are merged into the
    browser launch; `headers` are extra request headers.
    """

    id: int
    key: str
    name: str
    description: str
    client: str  # "http" | "browser"
    camoufox_options: Dict[str, Any] = field(default_factory=dict)
    headers: Dict[str, str] = field(default_factory=dict)
    #: What this rung adds over the one below, in operator-facing terms.
    isolates: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "key": self.key,
            "name": self.name,
            "description": self.description,
            "client": self.client,
            "isolates": self.isolates,
        }


#: A realistic modern Chrome UA on Windows, used from L2 up. L0/L1 deliberately
#: send the truth (or a default library UA) so the ladder has a naive baseline.
_CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)


EVASION_LEVELS: List[EvasionLevel] = [
    EvasionLevel(
        id=0,
        key="naive_http",
        name="L0 - Naive HTTP",
        description=(
            "Plain HTTP request with a default library User-Agent. No browser, "
            "no JavaScript, no cookies."
        ),
        client="http",
        isolates=(
            "The baseline everything else is measured against. If the defense "
            "cannot stop this, it is not protecting anything."
        ),
    ),
    EvasionLevel(
        id=1,
        key="headless_browser",
        name="L1 - Headless browser",
        description=(
            "Real Camoufox browser, headless, default fingerprint, no proxy, no "
            "humanization."
        ),
        client="browser",
        camoufox_options={"headless": True},
        isolates=(
            "Whether a stock headless browser is distinguishable at all. A "
            "defense that stops here is catching headless/automation tells, not "
            "fingerprint spoofing."
        ),
    ),
    EvasionLevel(
        id=2,
        key="header_consistency",
        name="L2 - Consistent headers",
        description=(
            "Headful browser with a coherent browser-like navigation profile: "
            "matching User-Agent, Accept, Accept-Language, Sec-Fetch-* and "
            "Referer."
        ),
        client="browser",
        camoufox_options={"headless": False},
        headers={
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "image/avif,image/webp,image/apng,*/*;q=0.8"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Cache-Control": "max-age=0",
        },
        isolates=(
            "Header-level anomaly detection. Catches a defense that keys on "
            "missing or contradictory navigation headers rather than on the "
            "browser itself."
        ),
    ),
    EvasionLevel(
        id=3,
        key="fingerprint_mask",
        name="L3 - Fingerprint masking",
        description=(
            "Camoufox fingerprint spoofing enabled: spoofed OS, screen, hardware "
            "concurrency, WebGL, fonts, navigator properties, with geoip and "
            "timezone aligned."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
        },
        headers={
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "image/avif,image/webp,image/apng,*/*;q=0.8"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
        },
        isolates=(
            "Fingerprint-based filtering: canvas/WebGL hashes, navigator "
            "inconsistencies, screen metrics. This is the rung that tests the "
            "anti-detect engine itself."
        ),
    ),
    EvasionLevel(
        id=4,
        key="proxy_rotation",
        name="L4 - Proxy rotation",
        description=(
            "Fingerprint masking plus a fresh exit IP per visitor from the "
            "configured proxy pool, with the fingerprint's locale aligned to the "
            "proxy's geo."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
        },
        headers={
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "image/avif,image/webp,image/apng,*/*;q=0.8"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
        },
        isolates=(
            "IP-reputation and rate-limit defenses. Tests whether the defense "
            "handles many distinct source IPs, i.e. whether it is only catching "
            "the easy single-IP case."
        ),
    ),
    EvasionLevel(
        id=5,
        key="behavioral",
        name="L5 - Human behavior",
        description=(
            "Proxy rotation plus a realistic visitor journey: plausible arrival "
            "source, dwell time, scrolling, mouse movement and typing at human "
            "cadence."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
        },
        headers={
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "image/avif,image/webp,image/apng,*/*;q=0.8"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
        },
        isolates=(
            "Behavioral / interaction analysis. Catches defenses that score "
            "mouse entropy, dwell time, or request cadence rather than the "
            "client's static properties."
        ),
    ),
    EvasionLevel(
        id=6,
        key="persistent_session",
        name="L6 - Persistent identity",
        description=(
            "Everything above, plus a persistent browser profile and cookies so "
            "the visitor returns as a recognized repeat visitor rather than a "
            "first-time client every time."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
            "persistent_context": True,
        },
        headers={
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "image/avif,image/webp,image/apng,*/*;q=0.8"
            ),
            "Accept-Language": "en-US,en;q=0.9",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
        },
        isolates=(
            "Reputation / trust scoring over time. Tests whether the defense "
            "escalates on a client whose cookies and profile it has seen."
        ),
    ),
]

_BY_ID = {level.id: level for level in EVASION_LEVELS}


def level_by_id(level_id: int) -> EvasionLevel:
    try:
        return _BY_ID[int(level_id)]
    except (KeyError, TypeError, ValueError):
        raise ValueError(
            f"Unknown evasion level {level_id!r}. Valid levels: "
            f"{sorted(_BY_ID)}"
        )


def levels_up_to(max_id: int) -> List[EvasionLevel]:
    """Levels 0..max_id inclusive, in order -- the usual way to run an audit."""
    return [level for level in EVASION_LEVELS if level.id <= int(max_id)]